import type { Metadata } from "next";
import Link from "next/link";
import { Download, Eye, ShieldAlert } from "lucide-react";

export const metadata: Metadata = {
  title: "Shared Resource",
  description: "Public share link surface for view-only and download-enabled resources.",
};

export default async function PublicSharePage({
  params,
}: {
  params: Promise<{ token: string }>;
}) {
  const { token } = await params;

  return (
    <main className="flex min-h-screen items-center justify-center px-6 py-16">
      <div className="w-full max-w-3xl rounded-[2rem] border border-ink-200/80 bg-white/82 p-8 shadow-[0_24px_80px_-48px_rgba(15,23,42,0.55)] backdrop-blur">
        <div className="flex flex-col gap-8 md:flex-row md:items-start md:justify-between">
          <div className="max-w-xl space-y-4">
            <p className="font-mono text-sm text-ink-500">Share token: {token}</p>
            <h1 className="text-4xl font-semibold tracking-[-0.05em] text-ink-950">
              Public link surface for secure previews and short-lived downloads.
            </h1>
            <p className="text-base leading-8 text-ink-700">
              This route is intentionally ready for expiry checks, password
              prompts, audit logging, and resource validation before access is
              granted.
            </p>
          </div>

          <div className="rounded-[1.5rem] border border-emerald-700/20 bg-emerald-700/8 p-5 text-sm text-emerald-900">
            <p className="flex items-center gap-2 font-medium">
              <ShieldAlert className="h-4 w-4" />
              Shared-link policy
            </p>
            <p className="mt-2 leading-7">
              Deleted, expired, or revoked resources should fail closed and
              never expose permanent storage URLs.
            </p>
          </div>
        </div>

        <div className="mt-8 grid gap-4 border-t border-ink-200/80 pt-8 md:grid-cols-2">
          <div className="rounded-[1.5rem] border border-ink-200/80 bg-surface-strong p-5">
            <p className="flex items-center gap-2 font-medium text-ink-950">
              <Eye className="h-4 w-4 text-emerald-700" />
              View-only mode
            </p>
            <p className="mt-3 text-sm leading-7 text-ink-600">
              Use this state for image and PDF previews with explicit file
              metadata, expiry, and ownership context.
            </p>
          </div>
          <div className="rounded-[1.5rem] border border-ink-200/80 bg-surface-strong p-5">
            <p className="flex items-center gap-2 font-medium text-ink-950">
              <Download className="h-4 w-4 text-emerald-700" />
              Download-enabled mode
            </p>
            <p className="mt-3 text-sm leading-7 text-ink-600">
              Gate this state behind permission checks and short-lived signed
              URLs generated by the app layer.
            </p>
          </div>
        </div>

        <div className="mt-8 flex gap-3">
          <Link
            href="/"
            className="rounded-full bg-ink-950 px-5 py-3 text-sm font-medium text-white transition hover:bg-ink-800"
          >
            Return home
          </Link>
          <Link
            href="/shared"
            className="rounded-full border border-ink-300 px-5 py-3 text-sm font-medium text-ink-800 transition hover:border-ink-500 hover:bg-white"
          >
            Inspect shared routes
          </Link>
        </div>
      </div>
    </main>
  );
}
